import type { Attribute, Category, Manufacturer } from "../types";

// All attributes in the library
export const attributeLibrary: Attribute[] = [
  // System attributes
  {
    id: "manufacturer",
    label: "Manufacturer",
    type: "dropdown",
    isSystem: true,
    isPreferred: true,
    appliedToCategories: [],
    description: "Equipment manufacturer",
    dropdownOptions: [
      "Vaillant",
      "Worcester Bosch",
      "Baxi",
      "Ideal",
      "Viessmann",
    ],
  },
  {
    id: "model",
    label: "Model",
    type: "dropdown",
    isSystem: true,
    isPreferred: true,
    appliedToCategories: [],
    description: "Equipment model",
    dropdownOptions: [
      "ecoTEC Plus",
      "Greenstar",
      "EcoBlue",
      "Logic",
      "Vitodens",
    ],
  },
  {
    id: "serial-number",
    label: "Serial Number",
    type: "text",
    isSystem: true,
    isPreferred: false,
    appliedToCategories: [],
    description: "Equipment serial number",
  },
  {
    id: "installation-date",
    label: "Installation Date",
    type: "date",
    isSystem: true,
    isPreferred: false,
    appliedToCategories: [],
    description: "Date of installation",
  },
  {
    id: "flue-type",
    label: "Flue Type",
    type: "dropdown",
    isSystem: true,
    isPreferred: false,
    appliedToCategories: ["boiler"],
    description: "Type of flue system",
    dropdownOptions: ["Horizontal", "Vertical", "Balanced Flue", "Open Flue"],
  },
  {
    id: "gas-pressure",
    label: "Gas Pressure",
    type: "number",
    isSystem: true,
    isPreferred: false,
    appliedToCategories: ["boiler"],
    description: "Gas pressure in mbar",
    units: "mbar",
  },
  {
    id: "capacity",
    label: "Capacity",
    type: "number",
    isSystem: true,
    isPreferred: false,
    appliedToCategories: [],
    description: "Equipment capacity",
  },
  {
    id: "voltage",
    label: "Voltage",
    type: "number",
    isSystem: true,
    isPreferred: false,
    appliedToCategories: [],
    description: "Operating voltage",
    units: "V",
  },
  // Custom attributes
  {
    id: "inspection-frequency",
    label: "Inspection Frequency",
    type: "dropdown",
    isSystem: false,
    isPreferred: false,
    appliedToCategories: [],
    description: "How often equipment should be inspected",
    dropdownOptions: ["Monthly", "Quarterly", "Annually", "Bi-annually"],
  },
  {
    id: "warranty-expiry",
    label: "Warranty Expiry",
    type: "date",
    isSystem: false,
    isPreferred: false,
    appliedToCategories: [],
    description: "Warranty expiration date",
  },
  {
    id: "location",
    label: "Location",
    type: "text",
    isSystem: false,
    isPreferred: false,
    appliedToCategories: [],
    description: "Physical location of the equipment",
  },
  {
    id: "pressure-rating",
    label: "Pressure Rating",
    type: "number",
    isSystem: false,
    isPreferred: false,
    appliedToCategories: [],
    description: "Maximum pressure rating in bar",
    units: "bar",
  },
];

// Hierarchical categories with the full tree structure
export const categories: Category[] = [
  // ==================== MECHANICAL ====================
  {
    id: "mechanical",
    name: "Mechanical",
    parentId: undefined,
    children: [
      "heating",
      "water-plumbing",
      "cooling-ventilation",
      "compressed-air",
      "power-generation",
      "fuel-storage",
      "misc-mechanical",
    ],
    systemAttributes: [],
    customAttributes: [],
  },

  // Heating
  {
    id: "heating",
    name: "Heating",
    parentId: "mechanical",
    children: [
      "boiler",
      "radiator",
      "underfloor-heating",
      "heat-pump-air",
      "heat-pump-ground",
      "expansion-vessel",
      "flue-system",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
      { attributeId: "serial-number", isEnabled: true, order: 2 },
      { attributeId: "installation-date", isEnabled: true, order: 3 },
    ],
    customAttributes: [
      { attributeId: "inspection-frequency", isEnabled: true, order: 0 },
      { attributeId: "warranty-expiry", isEnabled: true, order: 1 },
    ],
  },
  {
    id: "boiler",
    name: "Boiler",
    parentId: "heating",
    children: [],
    systemAttributes: [
      { attributeId: "flue-type", isEnabled: true, order: 4 },
      { attributeId: "gas-pressure", isEnabled: true, order: 5 },
      { attributeId: "capacity", isEnabled: true, order: 6 },
    ],
    customAttributes: [],
  },
  {
    id: "radiator",
    name: "Radiator / Heat Emitter",
    parentId: "heating",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "underfloor-heating",
    name: "Underfloor Heating Manifold",
    parentId: "heating",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "heat-pump-air",
    name: "Heat Pump (Air Source)",
    parentId: "heating",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 4 }],
    customAttributes: [],
  },
  {
    id: "heat-pump-ground",
    name: "Heat Pump (Ground Source)",
    parentId: "heating",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 4 }],
    customAttributes: [],
  },
  {
    id: "expansion-vessel",
    name: "Expansion Vessel",
    parentId: "heating",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 4 }],
    customAttributes: [
      { attributeId: "pressure-rating", isEnabled: true, order: 0 },
    ],
  },
  {
    id: "flue-system",
    name: "Flue / Exhaust System",
    parentId: "heating",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Water & Plumbing
  {
    id: "water-plumbing",
    name: "Water & Plumbing",
    parentId: "mechanical",
    children: [
      "cold-water-tank",
      "hot-water-cylinder",
      "water-booster",
      "pump",
      "valve",
      "pipework",
      "water-softener",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
      { attributeId: "installation-date", isEnabled: true, order: 2 },
    ],
    customAttributes: [
      { attributeId: "inspection-frequency", isEnabled: true, order: 0 },
    ],
  },
  {
    id: "cold-water-tank",
    name: "Cold Water Storage Tank",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 3 }],
    customAttributes: [],
  },
  {
    id: "hot-water-cylinder",
    name: "Hot Water Cylinder",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 3 }],
    customAttributes: [],
  },
  {
    id: "water-booster",
    name: "Water Booster Set / Pressurisation Unit",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "pump",
    name: "Pump (General / Circulation / Booster)",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 3 }],
    customAttributes: [],
  },
  {
    id: "valve",
    name: "Valve (Isolation / Control / Pressure Relief)",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [],
    customAttributes: [
      { attributeId: "pressure-rating", isEnabled: true, order: 0 },
    ],
  },
  {
    id: "pipework",
    name: "Pipework Section",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "water-softener",
    name: "Water Softener / Filter Unit",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Cooling & Ventilation
  {
    id: "cooling-ventilation",
    name: "Cooling & Ventilation",
    parentId: "mechanical",
    children: [
      "chiller",
      "fan-coil-unit",
      "cooling-tower",
      "air-handling-unit",
      "extractor-fan",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
      { attributeId: "installation-date", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "chiller",
    name: "Chiller",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 3 }],
    customAttributes: [],
  },
  {
    id: "fan-coil-unit",
    name: "Fan Coil Unit (FCU)",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "cooling-tower",
    name: "Cooling Tower",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "air-handling-unit",
    name: "Air Handling Unit (AHU)",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "extractor-fan",
    name: "Extractor Fan",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Compressed Air & Pressure Systems
  {
    id: "compressed-air",
    name: "Compressed Air & Pressure Systems",
    parentId: "mechanical",
    children: [
      "compressor",
      "receiver-tank",
      "dryer-filter",
      "pressure-regulator",
      "safety-relief-valve",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "compressor",
    name: "Compressor",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "receiver-tank",
    name: "Receiver / Air Tank",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "dryer-filter",
    name: "Dryer / Filter / Separator",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "pressure-regulator",
    name: "Pressure Regulator / Gauge",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "safety-relief-valve",
    name: "Safety Relief Valve",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Power Generation & Mechanical Drives
  {
    id: "power-generation",
    name: "Power Generation & Mechanical Drives",
    parentId: "mechanical",
    children: [
      "generator",
      "engine-motor",
      "coupling-shaft",
      "conveyor",
      "lift-pump",
      "belt-pulley",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "generator",
    name: "Generator (Diesel / Gas)",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "engine-motor",
    name: "Engine / Motor / Gearbox",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "coupling-shaft",
    name: "Coupling / Shaft",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "conveyor",
    name: "Conveyor",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "lift-pump",
    name: "Lift Pump",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "belt-pulley",
    name: "Belt / Pulley Assembly",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Fuel & Storage Systems
  {
    id: "fuel-storage",
    name: "Fuel & Storage Systems",
    parentId: "mechanical",
    children: ["fuel-tank", "fuel-transfer-pump", "pipework-bund"],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "fuel-tank",
    name: "Fuel Tank (Oil / Diesel)",
    parentId: "fuel-storage",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fuel-transfer-pump",
    name: "Fuel Transfer Pump",
    parentId: "fuel-storage",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "pipework-bund",
    name: "Pipework / Bund System",
    parentId: "fuel-storage",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Miscellaneous Mechanical Plant
  {
    id: "misc-mechanical",
    name: "Miscellaneous Mechanical Plant",
    parentId: "mechanical",
    children: [
      "mechanical-frame",
      "damper",
      "actuator-mechanical",
      "hydraulic-ram",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "mechanical-frame",
    name: "Mechanical Frame / Support",
    parentId: "misc-mechanical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "damper",
    name: "Damper",
    parentId: "misc-mechanical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "actuator-mechanical",
    name: "Actuator (Mechanical)",
    parentId: "misc-mechanical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "hydraulic-ram",
    name: "Hydraulic Ram / Cylinder",
    parentId: "misc-mechanical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // ==================== ELECTRICAL ====================
  {
    id: "electrical",
    name: "Electrical",
    parentId: undefined,
    children: [
      "distribution-switchgear",
      "power-quality",
      "ev-renewables",
      "general-electrical",
    ],
    systemAttributes: [],
    customAttributes: [],
  },

  // Distribution & Switchgear
  {
    id: "distribution-switchgear",
    name: "Distribution & Switchgear",
    parentId: "electrical",
    children: [
      "distribution-board",
      "switch-panel",
      "breaker-fuse",
      "surge-protection",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
      { attributeId: "voltage", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "distribution-board",
    name: "Distribution Board (DB)",
    parentId: "distribution-switchgear",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "switch-panel",
    name: "Switch Panel",
    parentId: "distribution-switchgear",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "breaker-fuse",
    name: "Breaker / Fuse",
    parentId: "distribution-switchgear",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "surge-protection",
    name: "Surge Protection Device",
    parentId: "distribution-switchgear",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Power Quality & Backup
  {
    id: "power-quality",
    name: "Power Quality & Backup",
    parentId: "electrical",
    children: ["ups", "generator-electrical", "power-conditioner"],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "ups",
    name: "UPS",
    parentId: "power-quality",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "generator-electrical",
    name: "Generator (Electrical Interface)",
    parentId: "power-quality",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "power-conditioner",
    name: "Power Conditioner",
    parentId: "power-quality",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // EV & Renewables
  {
    id: "ev-renewables",
    name: "EV & Renewables",
    parentId: "electrical",
    children: [
      "ev-charger",
      "solar-inverter",
      "solar-array",
      "battery-storage",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "ev-charger",
    name: "EV Charger",
    parentId: "ev-renewables",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "solar-inverter",
    name: "Solar PV Inverter",
    parentId: "ev-renewables",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "solar-array",
    name: "Solar PV Array",
    parentId: "ev-renewables",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "battery-storage",
    name: "Battery Storage Unit",
    parentId: "ev-renewables",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // General Electrical
  {
    id: "general-electrical",
    name: "General Electrical",
    parentId: "electrical",
    children: [
      "socket-outlet",
      "lighting-circuit",
      "control-panel",
      "cable-tray",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "socket-outlet",
    name: "Socket / Outlet",
    parentId: "general-electrical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "lighting-circuit",
    name: "Lighting Circuit",
    parentId: "general-electrical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "control-panel",
    name: "Control Panel",
    parentId: "general-electrical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "cable-tray",
    name: "Cable Tray / Containment",
    parentId: "general-electrical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // ==================== LIFE SAFETY ====================
  {
    id: "life-safety",
    name: "Life Safety",
    parentId: undefined,
    children: [
      "fire-alarm-systems",
      "emergency-lighting",
      "fire-suppression",
      "fire-safety-infrastructure",
    ],
    systemAttributes: [],
    customAttributes: [],
  },

  // Fire Alarm Systems
  {
    id: "fire-alarm-systems",
    name: "Fire Alarm Systems",
    parentId: "life-safety",
    children: [
      "fire-alarm-panel",
      "manual-call-point",
      "smoke-heat-detector",
      "sounder-beacon",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "fire-alarm-panel",
    name: "Fire Alarm Control Panel",
    parentId: "fire-alarm-systems",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "manual-call-point",
    name: "Manual Call Point",
    parentId: "fire-alarm-systems",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "smoke-heat-detector",
    name: "Smoke / Heat Detector",
    parentId: "fire-alarm-systems",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "sounder-beacon",
    name: "Sounder / Beacon",
    parentId: "fire-alarm-systems",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Emergency Lighting
  {
    id: "emergency-lighting",
    name: "Emergency Lighting",
    parentId: "life-safety",
    children: ["emergency-light-fitting"],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "emergency-light-fitting",
    name: "Emergency Light Fitting",
    parentId: "emergency-lighting",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Fire Suppression
  {
    id: "fire-suppression",
    name: "Fire Suppression",
    parentId: "life-safety",
    children: [
      "sprinkler-pump",
      "sprinkler-head",
      "gas-suppression-cylinder",
      "fire-extinguisher",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "sprinkler-pump",
    name: "Sprinkler Pump",
    parentId: "fire-suppression",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "sprinkler-head",
    name: "Sprinkler Head",
    parentId: "fire-suppression",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "gas-suppression-cylinder",
    name: "Gas Suppression Cylinder",
    parentId: "fire-suppression",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fire-extinguisher",
    name: "Fire Extinguisher",
    parentId: "fire-suppression",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Fire Safety Infrastructure
  {
    id: "fire-safety-infrastructure",
    name: "Fire Safety Infrastructure",
    parentId: "life-safety",
    children: ["fire-door", "fire-curtain", "fire-damper"],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fire-door",
    name: "Fire Door",
    parentId: "fire-safety-infrastructure",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fire-curtain",
    name: "Fire Curtain",
    parentId: "fire-safety-infrastructure",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fire-damper",
    name: "Fire Damper",
    parentId: "fire-safety-infrastructure",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // ==================== SECURITY ====================
  {
    id: "security",
    name: "Security",
    parentId: undefined,
    children: ["cctv", "intruder-alarm", "access-control"],
    systemAttributes: [],
    customAttributes: [],
  },

  // CCTV
  {
    id: "cctv",
    name: "CCTV",
    parentId: "security",
    children: ["cctv-camera", "nvr", "dvr", "cctv-power-supply"],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "cctv-camera",
    name: "CCTV Camera",
    parentId: "cctv",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "nvr",
    name: "Network Video Recorder (NVR)",
    parentId: "cctv",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "dvr",
    name: "DVR",
    parentId: "cctv",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "cctv-power-supply",
    name: "CCTV Power Supply",
    parentId: "cctv",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Intruder Alarm
  {
    id: "intruder-alarm",
    name: "Intruder Alarm",
    parentId: "security",
    children: [
      "intruder-alarm-panel",
      "pir-sensor",
      "door-contact",
      "siren-bell",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "intruder-alarm-panel",
    name: "Intruder Alarm Panel",
    parentId: "intruder-alarm",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "pir-sensor",
    name: "PIR Sensor",
    parentId: "intruder-alarm",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "door-contact",
    name: "Door Contact",
    parentId: "intruder-alarm",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "siren-bell",
    name: "Siren / Bell Box",
    parentId: "intruder-alarm",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Access Control
  {
    id: "access-control",
    name: "Access Control",
    parentId: "security",
    children: [
      "access-control-reader",
      "door-controller",
      "intercom",
      "electric-lock",
    ],
    systemAttributes: [
      { attributeId: "manufacturer", isEnabled: true, order: 0 },
      { attributeId: "model", isEnabled: true, order: 1 },
    ],
    customAttributes: [],
  },
  {
    id: "access-control-reader",
    name: "Access Control Reader",
    parentId: "access-control",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "door-controller",
    name: "Door Controller",
    parentId: "access-control",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "intercom",
    name: "Intercom",
    parentId: "access-control",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "electric-lock",
    name: "Electric Lock",
    parentId: "access-control",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
];

// Manufacturers with models
export const manufacturers: Manufacturer[] = [
  {
    id: "vaillant",
    name: "Vaillant",
    models: [
      { id: "ecotec-pro", name: "ecoTEC Pro" },
      { id: "ecotec-plus", name: "ecoTEC Plus" },
    ],
    usedByCategories: ["boiler"],
  },
  {
    id: "worcester-bosch",
    name: "Worcester Bosch",
    models: [
      { id: "greenstar", name: "Greenstar" },
      { id: "cdi-compact", name: "CDI Compact" },
    ],
    usedByCategories: ["boiler"],
  },
  {
    id: "grundfos",
    name: "Grundfos",
    models: [
      { id: "ups-series", name: "UPS Series" },
      { id: "magna-series", name: "Magna Series" },
    ],
    usedByCategories: ["pump"],
  },
  {
    id: "hikvision",
    name: "Hikvision",
    models: [
      { id: "ds-series", name: "DS Series" },
      { id: "colorvu", name: "ColorVu" },
    ],
    usedByCategories: ["cctv-camera", "nvr"],
  },
  {
    id: "honeywell",
    name: "Honeywell",
    models: [
      { id: "galaxy", name: "Galaxy" },
      { id: "dimension", name: "Dimension" },
    ],
    usedByCategories: ["fire-alarm-panel", "intruder-alarm-panel"],
  },
];
