export interface Job {
  id: string;
  jobRef: string;
  site: string;
  parent: string;
  completed: string;
  status: "Scheduled" | "In progress" | "Invoiced" | "Complete";
  selling: number;
  leftToInvoice: number;
  progress: number; // 0-100
  jobType: "home_repair" | "stacks";
  engineerName?: string;
  jobStartDate?: string;
  time?: string;
  resource?: string;
  vehicle?: string;
}

export const mockJobs: Job[] = [
  // Next Head Office sites (same parent, different sites)
  {
    id: "1",
    jobRef: "381910",
    site: "Next White Rose Leeds",
    parent: "Next Head Office",
    completed: "18 Mar 2024",
    status: "Scheduled",
    selling: 8393.0,
    leftToInvoice: 1000.0,
    progress: 85,
    jobType: "home_repair",
    engineerName: "John Smith",
    jobStartDate: "15 Mar 2024",
    time: "09:30 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "76",
    jobRef: "389283",
    site: "Next Arndale Manchester",
    parent: "Next Head Office",
    completed: "10 Apr 2024",
    status: "Complete",
    selling: 6500.0,
    leftToInvoice: 6500.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "James Wilson",
    jobStartDate: "8 Apr 2024",
    time: "09:00 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "77",
    jobRef: "389384",
    site: "Next Trafford Centre",
    parent: "Next Head Office",
    completed: "12 Apr 2024",
    status: "Complete",
    selling: 4200.0,
    leftToInvoice: 4200.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Sophie Taylor",
    jobStartDate: "10 Apr 2024",
    time: "10:30 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "78",
    jobRef: "389485",
    site: "Next Bull Ring Birmingham",
    parent: "Next Head Office",
    completed: "15 Apr 2024",
    status: "Complete",
    selling: 5800.0,
    leftToInvoice: 5800.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Oliver Brown",
    jobStartDate: "12 Apr 2024",
    time: "08:45 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "79",
    jobRef: "389586",
    site: "Next Kirkgate Leeds",
    parent: "Next Head Office",
    completed: "18 Apr 2024",
    status: "Complete",
    selling: 3900.0,
    leftToInvoice: 3900.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Emily Davis",
    jobStartDate: "16 Apr 2024",
    time: "09:15 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  // Additional Next Bull Ring Birmingham jobs
  {
    id: "100",
    jobRef: "391001",
    site: "Next Bull Ring Birmingham",
    parent: "Next Head Office",
    completed: "20 Apr 2024",
    status: "Complete",
    selling: 4200.0,
    leftToInvoice: 4200.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Ryan Mitchell",
    jobStartDate: "18 Apr 2024",
    time: "08:00 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "101",
    jobRef: "391002",
    site: "Next Bull Ring Birmingham",
    parent: "Next Head Office",
    completed: "22 Apr 2024",
    status: "Complete",
    selling: 5100.0,
    leftToInvoice: 5100.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Laura Bennett",
    jobStartDate: "20 Apr 2024",
    time: "09:30 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "102",
    jobRef: "391003",
    site: "Next Bull Ring Birmingham",
    parent: "Next Head Office",
    completed: "25 Apr 2024",
    status: "Complete",
    selling: 3800.0,
    leftToInvoice: 3800.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Mark Stevens",
    jobStartDate: "23 Apr 2024",
    time: "10:00 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "103",
    jobRef: "391004",
    site: "Next Bull Ring Birmingham",
    parent: "Next Head Office",
    completed: "28 Apr 2024",
    status: "Complete",
    selling: 6200.0,
    leftToInvoice: 6200.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Sarah Collins",
    jobStartDate: "26 Apr 2024",
    time: "08:45 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "104",
    jobRef: "391005",
    site: "Next Bull Ring Birmingham",
    parent: "Next Head Office",
    completed: "1 May 2024",
    status: "Complete",
    selling: 4700.0,
    leftToInvoice: 4700.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "David Hughes",
    jobStartDate: "29 Apr 2024",
    time: "09:00 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  // Additional Next Trafford Centre jobs
  {
    id: "105",
    jobRef: "391006",
    site: "Next Trafford Centre",
    parent: "Next Head Office",
    completed: "3 May 2024",
    status: "Complete",
    selling: 5500.0,
    leftToInvoice: 5500.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Emma Richards",
    jobStartDate: "1 May 2024",
    time: "08:30 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "106",
    jobRef: "391007",
    site: "Next Trafford Centre",
    parent: "Next Head Office",
    completed: "6 May 2024",
    status: "Complete",
    selling: 4300.0,
    leftToInvoice: 4300.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Chris Parker",
    jobStartDate: "4 May 2024",
    time: "10:15 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "107",
    jobRef: "391008",
    site: "Next Trafford Centre",
    parent: "Next Head Office",
    completed: "9 May 2024",
    status: "Complete",
    selling: 6800.0,
    leftToInvoice: 6800.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Rachel Cooper",
    jobStartDate: "7 May 2024",
    time: "08:00 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "108",
    jobRef: "391009",
    site: "Next Trafford Centre",
    parent: "Next Head Office",
    completed: "12 May 2024",
    status: "Complete",
    selling: 3900.0,
    leftToInvoice: 3900.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Andrew Morgan",
    jobStartDate: "10 May 2024",
    time: "09:45 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "109",
    jobRef: "391010",
    site: "Next Trafford Centre",
    parent: "Next Head Office",
    completed: "15 May 2024",
    status: "Complete",
    selling: 5200.0,
    leftToInvoice: 5200.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Jessica Ward",
    jobStartDate: "13 May 2024",
    time: "08:15 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  // Additional Next Arndale Manchester jobs
  {
    id: "110",
    jobRef: "391011",
    site: "Next Arndale Manchester",
    parent: "Next Head Office",
    completed: "18 May 2024",
    status: "Complete",
    selling: 7100.0,
    leftToInvoice: 7100.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Kevin Foster",
    jobStartDate: "16 May 2024",
    time: "07:30 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "111",
    jobRef: "391012",
    site: "Next Arndale Manchester",
    parent: "Next Head Office",
    completed: "21 May 2024",
    status: "Complete",
    selling: 4600.0,
    leftToInvoice: 4600.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Michelle Gray",
    jobStartDate: "19 May 2024",
    time: "09:00 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "112",
    jobRef: "391013",
    site: "Next Arndale Manchester",
    parent: "Next Head Office",
    completed: "24 May 2024",
    status: "Complete",
    selling: 5800.0,
    leftToInvoice: 5800.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Paul Turner",
    jobStartDate: "22 May 2024",
    time: "10:30 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "113",
    jobRef: "391014",
    site: "Next Arndale Manchester",
    parent: "Next Head Office",
    completed: "27 May 2024",
    status: "Complete",
    selling: 4100.0,
    leftToInvoice: 4100.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Natalie Scott",
    jobStartDate: "25 May 2024",
    time: "08:00 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "114",
    jobRef: "391015",
    site: "Next Arndale Manchester",
    parent: "Next Head Office",
    completed: "30 May 2024",
    status: "Complete",
    selling: 6300.0,
    leftToInvoice: 6300.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Steven Hill",
    jobStartDate: "28 May 2024",
    time: "09:15 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  // Additional Next White Rose Leeds jobs
  {
    id: "115",
    jobRef: "391016",
    site: "Next White Rose Leeds",
    parent: "Next Head Office",
    completed: "2 Jun 2024",
    status: "Complete",
    selling: 5400.0,
    leftToInvoice: 5400.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Claire Adams",
    jobStartDate: "31 May 2024",
    time: "08:30 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "116",
    jobRef: "391017",
    site: "Next White Rose Leeds",
    parent: "Next Head Office",
    completed: "5 Jun 2024",
    status: "Complete",
    selling: 4800.0,
    leftToInvoice: 4800.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Brian Nelson",
    jobStartDate: "3 Jun 2024",
    time: "10:00 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "117",
    jobRef: "391018",
    site: "Next White Rose Leeds",
    parent: "Next Head Office",
    completed: "8 Jun 2024",
    status: "Complete",
    selling: 7200.0,
    leftToInvoice: 7200.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Diana Carter",
    jobStartDate: "6 Jun 2024",
    time: "07:45 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "118",
    jobRef: "391019",
    site: "Next White Rose Leeds",
    parent: "Next Head Office",
    completed: "11 Jun 2024",
    status: "Complete",
    selling: 3600.0,
    leftToInvoice: 3600.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Frank Roberts",
    jobStartDate: "9 Jun 2024",
    time: "09:30 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "119",
    jobRef: "391020",
    site: "Next White Rose Leeds",
    parent: "Next Head Office",
    completed: "14 Jun 2024",
    status: "Complete",
    selling: 5900.0,
    leftToInvoice: 5900.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Helen Phillips",
    jobStartDate: "12 Jun 2024",
    time: "08:15 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  // John Lewis Head Office sites
  {
    id: "2",
    jobRef: "382011",
    site: "John Lewis Leeds",
    parent: "John Lewis Head Office",
    completed: "5 Mar – 25 Apr 2024",
    status: "In progress",
    selling: 7450.0,
    leftToInvoice: 500.0,
    progress: 95,
    jobType: "stacks",
    engineerName: "Sarah Johnson",
    jobStartDate: "5 Mar 2024",
    time: "08:00 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "3",
    jobRef: "382112",
    site: "John Lewis Liverpool",
    parent: "John Lewis Head Office",
    completed: "15 Jan – 30 Mar 2024",
    status: "In progress",
    selling: 9200.0,
    leftToInvoice: 1200.0,
    progress: 55,
    jobType: "stacks",
    engineerName: "Mike Williams",
    jobStartDate: "15 Jan 2024",
    time: "10:15 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "4",
    jobRef: "382112",
    site: "John Lewis Sheffield",
    parent: "John Lewis Head Office",
    completed: "15 Jan – 30 Mar 2024",
    status: "In progress",
    selling: 9200.0,
    leftToInvoice: 1200.0,
    progress: 55,
    jobType: "stacks",
    engineerName: "Emma Brown",
    jobStartDate: "15 Jan 2024",
    time: "11:00 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "5",
    jobRef: "382112",
    site: "John Lewis York",
    parent: "John Lewis Head Office",
    completed: "15 Jan – 30 Mar 2024",
    status: "In progress",
    selling: 9200.0,
    leftToInvoice: 1200.0,
    progress: 55,
    jobType: "stacks",
    engineerName: "David Lee",
    jobStartDate: "15 Jan 2024",
    time: "02:30 PM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "6",
    jobRef: "382213",
    site: "Next Yellow Daffodil Liverpool",
    parent: "Next Branch",
    completed: "20 Feb – 10 Apr 2024",
    status: "Invoiced",
    selling: 6850.0,
    leftToInvoice: 0.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Lisa Anderson",
    jobStartDate: "20 Feb 2024",
    time: "09:00 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "7",
    jobRef: "382314",
    site: "B&Q Manchester Central",
    parent: "B&Q Head Office",
    completed: "12 Apr 2024",
    status: "Scheduled",
    selling: 5200.0,
    leftToInvoice: 5200.0,
    progress: 0,
    jobType: "home_repair",
    engineerName: "Tom Wilson",
    jobStartDate: "12 Apr 2024",
    time: "08:45 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "8",
    jobRef: "382415",
    site: "IKEA Warrington",
    parent: "IKEA Head Office",
    completed: "1 Mar – 15 Apr 2024",
    status: "In progress",
    selling: 12500.0,
    leftToInvoice: 3500.0,
    progress: 72,
    jobType: "stacks",
    engineerName: "Rachel Green",
    jobStartDate: "1 Mar 2024",
    time: "10:00 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "9",
    jobRef: "382516",
    site: "Homebase Birmingham",
    parent: "Homebase UK",
    completed: "28 Feb 2024",
    status: "Complete",
    selling: 4300.0,
    leftToInvoice: 4300.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "10",
    jobRef: "382617",
    site: "Wickes Bradford",
    parent: "Wickes Group",
    completed: "10 Jan – 20 Mar 2024",
    status: "In progress",
    selling: 8750.0,
    leftToInvoice: 2100.0,
    progress: 76,
    jobType: "stacks",
  },
  {
    id: "11",
    jobRef: "382718",
    site: "Screwfix Newcastle",
    parent: "Screwfix Direct",
    completed: "5 Apr 2024",
    status: "Scheduled",
    selling: 3200.0,
    leftToInvoice: 3200.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "12",
    jobRef: "382819",
    site: "Toolstation Leeds",
    parent: "Toolstation Ltd",
    completed: "22 Feb – 8 Apr 2024",
    status: "In progress",
    selling: 6100.0,
    leftToInvoice: 1800.0,
    progress: 70,
    jobType: "stacks",
  },
  {
    id: "13",
    jobRef: "382920",
    site: "Travis Perkins Sheffield",
    parent: "Travis Perkins PLC",
    completed: "15 Mar 2024",
    status: "Complete",
    selling: 9500.0,
    leftToInvoice: 9500.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "14",
    jobRef: "383021",
    site: "Jewson Nottingham",
    parent: "Jewson Ltd",
    completed: "8 Feb – 30 Mar 2024",
    status: "In progress",
    selling: 7800.0,
    leftToInvoice: 2400.0,
    progress: 69,
    jobType: "stacks",
  },
  {
    id: "15",
    jobRef: "383122",
    site: "Selco Bristol",
    parent: "Selco Builders",
    completed: "20 Apr 2024",
    status: "Scheduled",
    selling: 4500.0,
    leftToInvoice: 4500.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "16",
    jobRef: "383223",
    site: "Howdens Southampton",
    parent: "Howdens Joinery",
    completed: "1 Feb – 25 Mar 2024",
    status: "Invoiced",
    selling: 11200.0,
    leftToInvoice: 0.0,
    progress: 100,
    jobType: "stacks",
  },
  {
    id: "17",
    jobRef: "383324",
    site: "MKM Building Supplies Derby",
    parent: "MKM Group",
    completed: "18 Mar 2024",
    status: "Complete",
    selling: 5600.0,
    leftToInvoice: 5600.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "18",
    jobRef: "383425",
    site: "Buildbase Leicester",
    parent: "Buildbase Ltd",
    completed: "12 Jan – 15 Apr 2024",
    status: "In progress",
    selling: 8900.0,
    leftToInvoice: 3200.0,
    progress: 64,
    jobType: "stacks",
  },
  {
    id: "19",
    jobRef: "383526",
    site: "Topps Tiles Coventry",
    parent: "Topps Tiles PLC",
    completed: "25 Apr 2024",
    status: "Scheduled",
    selling: 2800.0,
    leftToInvoice: 2800.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "20",
    jobRef: "383627",
    site: "Tile Giant Oxford",
    parent: "Tile Giant Ltd",
    completed: "5 Feb – 20 Mar 2024",
    status: "In progress",
    selling: 4100.0,
    leftToInvoice: 1200.0,
    progress: 71,
    jobType: "stacks",
  },
  {
    id: "21",
    jobRef: "383728",
    site: "CTD Tiles Cambridge",
    parent: "CTD Group",
    completed: "10 Mar 2024",
    status: "Complete",
    selling: 3500.0,
    leftToInvoice: 3500.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "22",
    jobRef: "383829",
    site: "Porcelanosa London",
    parent: "Porcelanosa UK",
    completed: "1 Jan – 28 Feb 2024",
    status: "Invoiced",
    selling: 15800.0,
    leftToInvoice: 0.0,
    progress: 100,
    jobType: "stacks",
  },
  {
    id: "23",
    jobRef: "383930",
    site: "Magnet Kitchens Glasgow",
    parent: "Magnet Ltd",
    completed: "22 Apr 2024",
    status: "Scheduled",
    selling: 7200.0,
    leftToInvoice: 7200.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "24",
    jobRef: "384031",
    site: "Wren Kitchens Edinburgh",
    parent: "Wren Kitchens Ltd",
    completed: "15 Feb – 10 Apr 2024",
    status: "In progress",
    selling: 18500.0,
    leftToInvoice: 6800.0,
    progress: 63,
    jobType: "stacks",
  },
  {
    id: "25",
    jobRef: "384132",
    site: "Symphony Kitchens Cardiff",
    parent: "Symphony Group",
    completed: "8 Mar 2024",
    status: "Complete",
    selling: 9800.0,
    leftToInvoice: 9800.0,
    progress: 100,
    jobType: "home_repair",
  },
  // Additional jobs for pagination testing
  {
    id: "26",
    jobRef: "384233",
    site: "Currys PC World Milton Keynes",
    parent: "Currys Group",
    completed: "5 May 2024",
    status: "Scheduled",
    selling: 4200.0,
    leftToInvoice: 4200.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "27",
    jobRef: "384334",
    site: "Argos Reading",
    parent: "Sainsbury's Argos",
    completed: "10 Mar – 20 Apr 2024",
    status: "In progress",
    selling: 6700.0,
    leftToInvoice: 2300.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "28",
    jobRef: "384435",
    site: "Halfords Bristol",
    parent: "Halfords Group",
    completed: "15 Apr 2024",
    status: "Complete",
    selling: 3100.0,
    leftToInvoice: 3100.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "29",
    jobRef: "384536",
    site: "Pets at Home Chester",
    parent: "Pets at Home Group",
    completed: "1 Feb – 28 Mar 2024",
    status: "In progress",
    selling: 5400.0,
    leftToInvoice: 1800.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "30",
    jobRef: "384637",
    site: "Sports Direct Newcastle",
    parent: "Frasers Group",
    completed: "25 Apr 2024",
    status: "Scheduled",
    selling: 8900.0,
    leftToInvoice: 8900.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "31",
    jobRef: "384738",
    site: "House of Fraser Birmingham",
    parent: "Frasers Group",
    completed: "20 Feb – 15 Apr 2024",
    status: "In progress",
    selling: 12300.0,
    leftToInvoice: 4100.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "32",
    jobRef: "384839",
    site: "Debenhams Manchester",
    parent: "Boohoo Group",
    completed: "10 Mar 2024",
    status: "Complete",
    selling: 7600.0,
    leftToInvoice: 7600.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "33",
    jobRef: "384940",
    site: "TK Maxx Liverpool",
    parent: "TJX Companies",
    completed: "5 Jan – 20 Mar 2024",
    status: "In progress",
    selling: 9200.0,
    leftToInvoice: 3100.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "34",
    jobRef: "385041",
    site: "Matalan Leeds",
    parent: "Matalan Retail",
    completed: "30 Apr 2024",
    status: "Scheduled",
    selling: 4800.0,
    leftToInvoice: 4800.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "35",
    jobRef: "385142",
    site: "Primark Sheffield",
    parent: "Associated British Foods",
    completed: "15 Feb – 10 Apr 2024",
    status: "In progress",
    selling: 15600.0,
    leftToInvoice: 5200.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "36",
    jobRef: "385243",
    site: "River Island Glasgow",
    parent: "River Island Fashion",
    completed: "20 Mar 2024",
    status: "Complete",
    selling: 6300.0,
    leftToInvoice: 6300.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "37",
    jobRef: "385344",
    site: "New Look Edinburgh",
    parent: "New Look Retail",
    completed: "1 Mar – 25 Apr 2024",
    status: "In progress",
    selling: 7100.0,
    leftToInvoice: 2400.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "38",
    jobRef: "385445",
    site: "H&M Cardiff",
    parent: "H&M Group",
    completed: "5 May 2024",
    status: "Scheduled",
    selling: 11200.0,
    leftToInvoice: 11200.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "39",
    jobRef: "385546",
    site: "Zara Bristol",
    parent: "Inditex Group",
    completed: "10 Feb – 5 Apr 2024",
    status: "In progress",
    selling: 13800.0,
    leftToInvoice: 4600.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "40",
    jobRef: "385647",
    site: "Uniqlo London",
    parent: "Fast Retailing",
    completed: "25 Mar 2024",
    status: "Complete",
    selling: 8400.0,
    leftToInvoice: 8400.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "41",
    jobRef: "385748",
    site: "Gap Oxford Street",
    parent: "Gap Inc",
    completed: "15 Jan – 30 Mar 2024",
    status: "In progress",
    selling: 9900.0,
    leftToInvoice: 3300.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "42",
    jobRef: "385849",
    site: "Superdry Brighton",
    parent: "Superdry PLC",
    completed: "10 May 2024",
    status: "Scheduled",
    selling: 5700.0,
    leftToInvoice: 5700.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "43",
    jobRef: "385950",
    site: "Ted Baker Nottingham",
    parent: "Authentic Brands",
    completed: "20 Feb – 15 Apr 2024",
    status: "In progress",
    selling: 7800.0,
    leftToInvoice: 2600.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "44",
    jobRef: "386051",
    site: "Moss Bros Leicester",
    parent: "Moss Bros Group",
    completed: "5 Apr 2024",
    status: "Complete",
    selling: 4100.0,
    leftToInvoice: 4100.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "45",
    jobRef: "386152",
    site: "Clarks Southampton",
    parent: "Clarks Shoes",
    completed: "1 Mar – 20 Apr 2024",
    status: "In progress",
    selling: 6200.0,
    leftToInvoice: 2100.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "46",
    jobRef: "386253",
    site: "Schuh Coventry",
    parent: "Genesco Inc",
    completed: "15 May 2024",
    status: "Scheduled",
    selling: 3800.0,
    leftToInvoice: 3800.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "47",
    jobRef: "386354",
    site: "JD Sports Wolverhampton",
    parent: "JD Sports Fashion",
    completed: "10 Feb – 5 Apr 2024",
    status: "In progress",
    selling: 8600.0,
    leftToInvoice: 2900.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "48",
    jobRef: "386455",
    site: "Footlocker Sunderland",
    parent: "Foot Locker Inc",
    completed: "30 Mar 2024",
    status: "Complete",
    selling: 5900.0,
    leftToInvoice: 5900.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "49",
    jobRef: "386556",
    site: "Size? Middlesbrough",
    parent: "JD Sports Fashion",
    completed: "25 Jan – 15 Apr 2024",
    status: "In progress",
    selling: 4300.0,
    leftToInvoice: 1400.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "50",
    jobRef: "386657",
    site: "Office Shoes York",
    parent: "Office Holdings",
    completed: "20 May 2024",
    status: "Scheduled",
    selling: 2900.0,
    leftToInvoice: 2900.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "51",
    jobRef: "386758",
    site: "Kurt Geiger Harrogate",
    parent: "Kurt Geiger Ltd",
    completed: "5 Mar – 25 Apr 2024",
    status: "In progress",
    selling: 7400.0,
    leftToInvoice: 2500.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "52",
    jobRef: "386859",
    site: "Boots Pharmacy Hull",
    parent: "Walgreens Boots Alliance",
    completed: "10 Apr 2024",
    status: "Complete",
    selling: 6100.0,
    leftToInvoice: 6100.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "53",
    jobRef: "386960",
    site: "Superdrug Grimsby",
    parent: "A.S. Watson Group",
    completed: "15 Feb – 10 Apr 2024",
    status: "In progress",
    selling: 3600.0,
    leftToInvoice: 1200.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "54",
    jobRef: "387061",
    site: "Savers Scunthorpe",
    parent: "A.S. Watson Group",
    completed: "25 May 2024",
    status: "Scheduled",
    selling: 2100.0,
    leftToInvoice: 2100.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "55",
    jobRef: "387162",
    site: "Lloyds Pharmacy Doncaster",
    parent: "Aurelius Equity",
    completed: "20 Jan – 15 Mar 2024",
    status: "In progress",
    selling: 4800.0,
    leftToInvoice: 1600.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "56",
    jobRef: "387263",
    site: "Holland & Barrett Rotherham",
    parent: "The Nature's Bounty Co",
    completed: "5 Apr 2024",
    status: "Complete",
    selling: 3200.0,
    leftToInvoice: 3200.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "57",
    jobRef: "387364",
    site: "The Body Shop Barnsley",
    parent: "Natura & Co",
    completed: "10 Mar – 30 Apr 2024",
    status: "In progress",
    selling: 5100.0,
    leftToInvoice: 1700.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "58",
    jobRef: "387465",
    site: "Lush Wakefield",
    parent: "Lush Ltd",
    completed: "30 May 2024",
    status: "Scheduled",
    selling: 4400.0,
    leftToInvoice: 4400.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "59",
    jobRef: "387566",
    site: "Space NK Huddersfield",
    parent: "Manzanita Capital",
    completed: "25 Feb – 20 Apr 2024",
    status: "In progress",
    selling: 6800.0,
    leftToInvoice: 2300.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "60",
    jobRef: "387667",
    site: "Sephora Bradford",
    parent: "LVMH",
    completed: "15 Apr 2024",
    status: "Complete",
    selling: 9300.0,
    leftToInvoice: 9300.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "61",
    jobRef: "387768",
    site: "Waterstones Halifax",
    parent: "Elliott Advisors",
    completed: "5 Feb – 25 Mar 2024",
    status: "In progress",
    selling: 4600.0,
    leftToInvoice: 1500.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "62",
    jobRef: "387869",
    site: "WHSmith Preston",
    parent: "WHSmith PLC",
    completed: "5 Jun 2024",
    status: "Scheduled",
    selling: 3700.0,
    leftToInvoice: 3700.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "63",
    jobRef: "387970",
    site: "Ryman Blackburn",
    parent: "Ryman Group",
    completed: "20 Mar – 15 May 2024",
    status: "In progress",
    selling: 2800.0,
    leftToInvoice: 900.0,
    progress: 68,
    jobType: "stacks",
  },
  {
    id: "64",
    jobRef: "388071",
    site: "Staples Bolton",
    parent: "Staples Inc",
    completed: "25 Apr 2024",
    status: "Complete",
    selling: 5400.0,
    leftToInvoice: 5400.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "65",
    jobRef: "388172",
    site: "Smyths Toys Bury",
    parent: "Smyths Toys Group",
    completed: "10 Jan – 5 Apr 2024",
    status: "In progress",
    selling: 8100.0,
    leftToInvoice: 2700.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "66",
    jobRef: "388273",
    site: "The Entertainer Oldham",
    parent: "The Entertainer Group",
    completed: "10 Jun 2024",
    status: "Scheduled",
    selling: 4900.0,
    leftToInvoice: 4900.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "67",
    jobRef: "388374",
    site: "Build-A-Bear Stockport",
    parent: "Build-A-Bear Workshop",
    completed: "15 Feb – 10 Apr 2024",
    status: "In progress",
    selling: 3400.0,
    leftToInvoice: 1100.0,
    progress: 68,
    jobType: "stacks",
  },
  {
    id: "68",
    jobRef: "388475",
    site: "Game Ashton",
    parent: "Frasers Group",
    completed: "5 May 2024",
    status: "Complete",
    selling: 6200.0,
    leftToInvoice: 6200.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "69",
    jobRef: "388576",
    site: "CeX Rochdale",
    parent: "CeX Ltd",
    completed: "25 Mar – 20 May 2024",
    status: "In progress",
    selling: 2600.0,
    leftToInvoice: 900.0,
    progress: 65,
    jobType: "stacks",
  },
  {
    id: "70",
    jobRef: "388677",
    site: "Music Magpie Wigan",
    parent: "musicMagpie PLC",
    completed: "15 Jun 2024",
    status: "Scheduled",
    selling: 1800.0,
    leftToInvoice: 1800.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "71",
    jobRef: "388778",
    site: "Currys Warrington",
    parent: "Currys Group",
    completed: "1 Mar – 25 Apr 2024",
    status: "In progress",
    selling: 7300.0,
    leftToInvoice: 2400.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "72",
    jobRef: "388879",
    site: "AO.com Crewe",
    parent: "AO World PLC",
    completed: "10 May 2024",
    status: "Complete",
    selling: 8700.0,
    leftToInvoice: 8700.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "73",
    jobRef: "388980",
    site: "Euronics Stoke",
    parent: "Euronics International",
    completed: "20 Feb – 15 Apr 2024",
    status: "In progress",
    selling: 4100.0,
    leftToInvoice: 1400.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "74",
    jobRef: "389081",
    site: "Hughes Electrical Derby",
    parent: "Hughes Electrical",
    completed: "20 Jun 2024",
    status: "Scheduled",
    selling: 5600.0,
    leftToInvoice: 5600.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "75",
    jobRef: "389182",
    site: "Robert Dyas Northampton",
    parent: "Robert Dyas Holdings",
    completed: "5 Mar – 30 Apr 2024",
    status: "In progress",
    selling: 3900.0,
    leftToInvoice: 1300.0,
    progress: 67,
    jobType: "stacks",
  },
  // Tesco Head Office sites (new parent with multiple sites)
  {
    id: "80",
    jobRef: "389687",
    site: "Tesco Extra Leeds",
    parent: "Tesco Head Office",
    completed: "20 Apr 2024",
    status: "Complete",
    selling: 7200.0,
    leftToInvoice: 7200.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Daniel Harris",
    jobStartDate: "18 Apr 2024",
    time: "07:30 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "81",
    jobRef: "389788",
    site: "Tesco Metro Manchester",
    parent: "Tesco Head Office",
    completed: "22 Apr 2024",
    status: "Complete",
    selling: 4500.0,
    leftToInvoice: 4500.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Charlotte Martin",
    jobStartDate: "20 Apr 2024",
    time: "08:00 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "82",
    jobRef: "389889",
    site: "Tesco Superstore Liverpool",
    parent: "Tesco Head Office",
    completed: "25 Apr 2024",
    status: "Complete",
    selling: 8100.0,
    leftToInvoice: 8100.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Jack Thompson",
    jobStartDate: "22 Apr 2024",
    time: "09:00 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "83",
    jobRef: "389990",
    site: "Tesco Express Birmingham",
    parent: "Tesco Head Office",
    completed: "28 Apr 2024",
    status: "Complete",
    selling: 3200.0,
    leftToInvoice: 3200.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Amelia White",
    jobStartDate: "26 Apr 2024",
    time: "10:15 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "84",
    jobRef: "390091",
    site: "Tesco Extra Sheffield",
    parent: "Tesco Head Office",
    completed: "1 May 2024",
    status: "Complete",
    selling: 6800.0,
    leftToInvoice: 6800.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "George Jackson",
    jobStartDate: "28 Apr 2024",
    time: "08:30 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  // Boots UK sites (new parent with multiple sites)
  {
    id: "85",
    jobRef: "390192",
    site: "Boots Pharmacy Leeds",
    parent: "Boots UK",
    completed: "3 May 2024",
    status: "Complete",
    selling: 5500.0,
    leftToInvoice: 5500.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Isabella Robinson",
    jobStartDate: "1 May 2024",
    time: "09:00 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "86",
    jobRef: "390293",
    site: "Boots Opticians Manchester",
    parent: "Boots UK",
    completed: "5 May 2024",
    status: "Complete",
    selling: 4100.0,
    leftToInvoice: 4100.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Harry Clark",
    jobStartDate: "3 May 2024",
    time: "10:00 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "87",
    jobRef: "390394",
    site: "Boots Pharmacy Liverpool",
    parent: "Boots UK",
    completed: "8 May 2024",
    status: "Complete",
    selling: 6200.0,
    leftToInvoice: 6200.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Mia Lewis",
    jobStartDate: "5 May 2024",
    time: "08:45 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "88",
    jobRef: "390495",
    site: "Boots Pharmacy Birmingham",
    parent: "Boots UK",
    completed: "10 May 2024",
    status: "Complete",
    selling: 4800.0,
    leftToInvoice: 4800.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Oscar Walker",
    jobStartDate: "8 May 2024",
    time: "09:30 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  // Sainsbury's Head Office sites (new parent with multiple sites)
  {
    id: "89",
    jobRef: "390596",
    site: "Sainsbury's Local Leeds",
    parent: "Sainsbury's Head Office",
    completed: "12 May 2024",
    status: "Complete",
    selling: 3800.0,
    leftToInvoice: 3800.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Lily Young",
    jobStartDate: "10 May 2024",
    time: "08:00 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "90",
    jobRef: "390697",
    site: "Sainsbury's Superstore Manchester",
    parent: "Sainsbury's Head Office",
    completed: "15 May 2024",
    status: "Complete",
    selling: 9500.0,
    leftToInvoice: 9500.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Jacob Hall",
    jobStartDate: "12 May 2024",
    time: "07:45 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
  {
    id: "91",
    jobRef: "390798",
    site: "Sainsbury's Local Liverpool",
    parent: "Sainsbury's Head Office",
    completed: "18 May 2024",
    status: "Complete",
    selling: 4200.0,
    leftToInvoice: 4200.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Grace Allen",
    jobStartDate: "16 May 2024",
    time: "09:00 AM",
    resource: "Engineer Team A",
    vehicle: "Van-123",
  },
  {
    id: "92",
    jobRef: "390899",
    site: "Sainsbury's Superstore Birmingham",
    parent: "Sainsbury's Head Office",
    completed: "20 May 2024",
    status: "Complete",
    selling: 8700.0,
    leftToInvoice: 8700.0,
    progress: 100,
    jobType: "stacks",
    engineerName: "Thomas King",
    jobStartDate: "18 May 2024",
    time: "08:15 AM",
    resource: "Engineer Team B",
    vehicle: "Van-456",
  },
  {
    id: "93",
    jobRef: "390999",
    site: "Sainsbury's Local Sheffield",
    parent: "Sainsbury's Head Office",
    completed: "22 May 2024",
    status: "Complete",
    selling: 3500.0,
    leftToInvoice: 3500.0,
    progress: 100,
    jobType: "home_repair",
    engineerName: "Ava Wright",
    jobStartDate: "20 May 2024",
    time: "10:00 AM",
    resource: "Engineer Team C",
    vehicle: "Van-789",
  },
];

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    minimumFractionDigits: 2,
  }).format(amount);
}
