import type {
  Attribute,
  Category,
  Manufacturer,
  CoreAttribute,
} from "../types";

// Pre-defined category-specific attributes (can be toggled on/off but not edited)
// Each category can have its own set of pre-defined attributes
export const predefinedCategoryAttributes: Record<string, Attribute[]> = {
  boiler: [
    {
      id: "flue-type",
      label: "Flue Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of flue system",
      dropdownOptions: ["Horizontal", "Vertical", "Balanced Flue", "Open Flue"],
    },
    {
      id: "gas-pressure",
      label: "Gas Pressure",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Gas pressure in mbar",
      units: "mbar",
    },
    {
      id: "capacity",
      label: "Capacity",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Equipment capacity",
    },
  ],
  "expansion-vessel": [
    {
      id: "capacity",
      label: "Capacity",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Equipment capacity",
    },
  ],
  "cold-water-tank": [
    {
      id: "capacity",
      label: "Capacity",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Equipment capacity",
    },
  ],
  "hot-water-cylinder": [
    {
      id: "capacity",
      label: "Capacity",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Equipment capacity",
    },
  ],
  pump: [
    {
      id: "capacity",
      label: "Capacity",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Equipment capacity",
    },
  ],
  "distribution-switchgear": [
    {
      id: "voltage",
      label: "Voltage",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Operating voltage",
      units: "V",
    },
  ],
  radiator: [
    {
      id: "btu-output",
      label: "BTU Output",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Heat output rating in BTU",
      units: "BTU",
    },
    {
      id: "valve-type",
      label: "Valve Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of radiator valve",
      dropdownOptions: ["Manual", "Thermostatic", "Lock Shield", "Lockshield"],
    },
    {
      id: "sections",
      label: "Number of Sections",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Number of radiator sections",
    },
  ],
  chiller: [
    {
      id: "capacity",
      label: "Capacity",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Equipment capacity",
    },
    {
      id: "refrigerant-type",
      label: "Refrigerant Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of refrigerant used",
      dropdownOptions: ["R134a", "R410A", "R407C", "R22", "R32", "R1234ze"],
    },
    {
      id: "compressor-type",
      label: "Compressor Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of compressor",
      dropdownOptions: ["Scroll", "Screw", "Centrifugal", "Reciprocating"],
    },
  ],
  "ev-charger": [
    {
      id: "charging-power",
      label: "Charging Power",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Maximum charging power",
      units: "kW",
    },
    {
      id: "connector-type",
      label: "Connector Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of charging connector",
      dropdownOptions: ["Type 2", "CCS", "CHAdeMO", "Type 1", "Tesla"],
    },
    {
      id: "phase",
      label: "Phase",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Electrical phase configuration",
      dropdownOptions: ["Single Phase", "Three Phase"],
    },
  ],
  "cctv-camera": [
    {
      id: "resolution",
      label: "Resolution",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Camera resolution",
      dropdownOptions: ["720p", "1080p", "2MP", "4MP", "5MP", "8MP", "12MP"],
    },
    {
      id: "night-vision-range",
      label: "Night Vision Range",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Infrared night vision range",
      units: "m",
    },
    {
      id: "ptz-capability",
      label: "PTZ Capability",
      type: "boolean",
      isSystem: true,
      isPreferred: false,
      description: "Pan-tilt-zoom capability",
    },
  ],
  "heat-pump-air": [
    {
      id: "capacity",
      label: "Capacity",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Equipment capacity",
    },
    {
      id: "cop-rating",
      label: "COP Rating",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Coefficient of Performance rating",
    },
    {
      id: "refrigerant-type",
      label: "Refrigerant Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of refrigerant used",
      dropdownOptions: ["R134a", "R410A", "R407C", "R32", "R1234ze"],
    },
  ],
  "heat-pump-ground": [
    {
      id: "capacity",
      label: "Capacity",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Equipment capacity",
    },
    {
      id: "cop-rating",
      label: "COP Rating",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Coefficient of Performance rating",
    },
    {
      id: "ground-loop-type",
      label: "Ground Loop Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of ground loop system",
      dropdownOptions: ["Horizontal", "Vertical", "Slinky", "Pond/Lake"],
    },
  ],
  "air-handling-unit": [
    {
      id: "air-flow-rate",
      label: "Air Flow Rate",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Maximum air flow rate",
      units: "m³/h",
    },
    {
      id: "filter-type",
      label: "Filter Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of air filter",
      dropdownOptions: ["G4", "G5", "F7", "F8", "F9", "HEPA", "Carbon"],
    },
    {
      id: "heat-recovery",
      label: "Heat Recovery",
      type: "boolean",
      isSystem: true,
      isPreferred: false,
      description: "Heat recovery capability",
    },
  ],
  compressor: [
    {
      id: "discharge-pressure",
      label: "Discharge Pressure",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Maximum discharge pressure",
      units: "bar",
    },
    {
      id: "cfm-rating",
      label: "CFM Rating",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Cubic feet per minute rating",
      units: "CFM",
    },
    {
      id: "compressor-type",
      label: "Compressor Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of compressor",
      dropdownOptions: ["Reciprocating", "Rotary Screw", "Scroll", "Centrifugal"],
    },
  ],
  generator: [
    {
      id: "rated-power",
      label: "Rated Power",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Rated power output",
      units: "kW",
    },
    {
      id: "fuel-type",
      label: "Fuel Type",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Type of fuel used",
      dropdownOptions: ["Diesel", "Gas", "Petrol", "Natural Gas", "LPG"],
    },
    {
      id: "phase",
      label: "Phase",
      type: "dropdown",
      isSystem: true,
      isPreferred: false,
      description: "Electrical phase configuration",
      dropdownOptions: ["Single Phase", "Three Phase"],
    },
  ],
  ups: [
    {
      id: "rated-power",
      label: "Rated Power",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Rated power output",
      units: "kVA",
    },
    {
      id: "battery-runtime",
      label: "Battery Runtime",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Battery backup runtime",
      units: "min",
    },
    {
      id: "output-voltage",
      label: "Output Voltage",
      type: "number",
      isSystem: true,
      isPreferred: false,
      description: "Output voltage",
      units: "V",
    },
  ],
};

// Hierarchical categories with the full tree structure
export const categories: Category[] = [
  // ==================== MECHANICAL ====================

  // Heating
  {
    id: "heating",
    name: "Heating",
    parentId: undefined,
    children: [
      "boiler",
      "radiator",
      "underfloor-heating",
      "heat-pump-air",
      "heat-pump-ground",
      "expansion-vessel",
      "flue-system",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "boiler",
    name: "Boiler",
    parentId: "heating",
    children: [],
    systemAttributes: [
      { attributeId: "flue-type", isEnabled: true, order: 0 },
      { attributeId: "gas-pressure", isEnabled: true, order: 1 },
      { attributeId: "capacity", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "radiator",
    name: "Radiator / Heat Emitter",
    parentId: "heating",
    children: [],
    systemAttributes: [
      { attributeId: "btu-output", isEnabled: true, order: 0 },
      { attributeId: "valve-type", isEnabled: true, order: 1 },
      { attributeId: "sections", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "underfloor-heating",
    name: "Underfloor Heating Manifold",
    parentId: "heating",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "heat-pump-air",
    name: "Heat Pump (Air Source)",
    parentId: "heating",
    children: [],
    systemAttributes: [
      { attributeId: "capacity", isEnabled: true, order: 0 },
      { attributeId: "cop-rating", isEnabled: true, order: 1 },
      { attributeId: "refrigerant-type", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "heat-pump-ground",
    name: "Heat Pump (Ground Source)",
    parentId: "heating",
    children: [],
    systemAttributes: [
      { attributeId: "capacity", isEnabled: true, order: 0 },
      { attributeId: "cop-rating", isEnabled: true, order: 1 },
      { attributeId: "ground-loop-type", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "expansion-vessel",
    name: "Expansion Vessel",
    parentId: "heating",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 0 }],
    customAttributes: [],
  },
  {
    id: "flue-system",
    name: "Flue / Exhaust System",
    parentId: "heating",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Water & Plumbing
  {
    id: "water-plumbing",
    name: "Water & Plumbing",
    parentId: undefined,
    children: [
      "cold-water-tank",
      "hot-water-cylinder",
      "water-booster",
      "pump",
      "valve",
      "pipework",
      "water-softener",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "cold-water-tank",
    name: "Cold Water Storage Tank",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 0 }],
    customAttributes: [],
  },
  {
    id: "hot-water-cylinder",
    name: "Hot Water Cylinder",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 0 }],
    customAttributes: [],
  },
  {
    id: "water-booster",
    name: "Water Booster Set / Pressurisation Unit",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "pump",
    name: "Pump (General / Circulation / Booster)",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [{ attributeId: "capacity", isEnabled: true, order: 0 }],
    customAttributes: [],
  },
  {
    id: "valve",
    name: "Valve (Isolation / Control / Pressure Relief)",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "pipework",
    name: "Pipework Section",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "water-softener",
    name: "Water Softener / Filter Unit",
    parentId: "water-plumbing",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Cooling & Ventilation
  {
    id: "cooling-ventilation",
    name: "Cooling & Ventilation",
    parentId: undefined,
    children: [
      "chiller",
      "fan-coil-unit",
      "cooling-tower",
      "air-handling-unit",
      "extractor-fan",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "chiller",
    name: "Chiller",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [
      { attributeId: "capacity", isEnabled: true, order: 0 },
      { attributeId: "refrigerant-type", isEnabled: true, order: 1 },
      { attributeId: "compressor-type", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "fan-coil-unit",
    name: "Fan Coil Unit (FCU)",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "cooling-tower",
    name: "Cooling Tower",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "air-handling-unit",
    name: "Air Handling Unit (AHU)",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [
      { attributeId: "air-flow-rate", isEnabled: true, order: 0 },
      { attributeId: "filter-type", isEnabled: true, order: 1 },
      { attributeId: "heat-recovery", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "extractor-fan",
    name: "Extractor Fan",
    parentId: "cooling-ventilation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Compressed Air & Pressure Systems
  {
    id: "compressed-air",
    name: "Compressed Air & Pressure Systems",
    parentId: undefined,
    children: [
      "compressor",
      "receiver-tank",
      "dryer-filter",
      "pressure-regulator",
      "safety-relief-valve",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "compressor",
    name: "Compressor",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [
      { attributeId: "discharge-pressure", isEnabled: true, order: 0 },
      { attributeId: "cfm-rating", isEnabled: true, order: 1 },
      { attributeId: "compressor-type", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "receiver-tank",
    name: "Receiver / Air Tank",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "dryer-filter",
    name: "Dryer / Filter / Separator",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "pressure-regulator",
    name: "Pressure Regulator / Gauge",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "safety-relief-valve",
    name: "Safety Relief Valve",
    parentId: "compressed-air",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Power Generation & Mechanical Drives
  {
    id: "power-generation",
    name: "Power Generation & Mechanical Drives",
    parentId: undefined,
    children: [
      "generator",
      "engine-motor",
      "coupling-shaft",
      "conveyor",
      "lift-pump",
      "belt-pulley",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "generator",
    name: "Generator (Diesel / Gas)",
    parentId: "power-generation",
    children: [],
    systemAttributes: [
      { attributeId: "rated-power", isEnabled: true, order: 0 },
      { attributeId: "fuel-type", isEnabled: true, order: 1 },
      { attributeId: "phase", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "engine-motor",
    name: "Engine / Motor / Gearbox",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "coupling-shaft",
    name: "Coupling / Shaft",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "conveyor",
    name: "Conveyor",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "lift-pump",
    name: "Lift Pump",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "belt-pulley",
    name: "Belt / Pulley Assembly",
    parentId: "power-generation",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Fuel & Storage Systems
  {
    id: "fuel-storage",
    name: "Fuel & Storage Systems",
    parentId: undefined,
    children: ["fuel-tank", "fuel-transfer-pump", "pipework-bund"],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fuel-tank",
    name: "Fuel Tank (Oil / Diesel)",
    parentId: "fuel-storage",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fuel-transfer-pump",
    name: "Fuel Transfer Pump",
    parentId: "fuel-storage",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "pipework-bund",
    name: "Pipework / Bund System",
    parentId: "fuel-storage",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Miscellaneous Mechanical Plant
  {
    id: "misc-mechanical",
    name: "Miscellaneous Mechanical Plant",
    parentId: undefined,
    children: [
      "mechanical-frame",
      "damper",
      "actuator-mechanical",
      "hydraulic-ram",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "mechanical-frame",
    name: "Mechanical Frame / Support",
    parentId: "misc-mechanical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "damper",
    name: "Damper",
    parentId: "misc-mechanical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "actuator-mechanical",
    name: "Actuator (Mechanical)",
    parentId: "misc-mechanical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "hydraulic-ram",
    name: "Hydraulic Ram / Cylinder",
    parentId: "misc-mechanical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // ==================== ELECTRICAL ====================

  // Distribution & Switchgear
  {
    id: "distribution-switchgear",
    name: "Distribution & Switchgear",
    parentId: undefined,
    children: [
      "distribution-board",
      "switch-panel",
      "breaker-fuse",
      "surge-protection",
    ],
    systemAttributes: [
      { attributeId: "voltage", isEnabled: true, order: 0 },
    ],
    customAttributes: [],
  },
  {
    id: "distribution-board",
    name: "Distribution Board (DB)",
    parentId: "distribution-switchgear",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "switch-panel",
    name: "Switch Panel",
    parentId: "distribution-switchgear",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "breaker-fuse",
    name: "Breaker / Fuse",
    parentId: "distribution-switchgear",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "surge-protection",
    name: "Surge Protection Device",
    parentId: "distribution-switchgear",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Power Quality & Backup
  {
    id: "power-quality",
    name: "Power Quality & Backup",
    parentId: undefined,
    children: ["ups", "generator-electrical", "power-conditioner"],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "ups",
    name: "UPS",
    parentId: "power-quality",
    children: [],
    systemAttributes: [
      { attributeId: "rated-power", isEnabled: true, order: 0 },
      { attributeId: "battery-runtime", isEnabled: true, order: 1 },
      { attributeId: "output-voltage", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "generator-electrical",
    name: "Generator (Electrical Interface)",
    parentId: "power-quality",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "power-conditioner",
    name: "Power Conditioner",
    parentId: "power-quality",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // EV & Renewables
  {
    id: "ev-renewables",
    name: "EV & Renewables",
    parentId: undefined,
    children: [
      "ev-charger",
      "solar-inverter",
      "solar-array",
      "battery-storage",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "ev-charger",
    name: "EV Charger",
    parentId: "ev-renewables",
    children: [],
    systemAttributes: [
      { attributeId: "charging-power", isEnabled: true, order: 0 },
      { attributeId: "connector-type", isEnabled: true, order: 1 },
      { attributeId: "phase", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "solar-inverter",
    name: "Solar PV Inverter",
    parentId: "ev-renewables",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "solar-array",
    name: "Solar PV Array",
    parentId: "ev-renewables",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "battery-storage",
    name: "Battery Storage Unit",
    parentId: "ev-renewables",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // General Electrical
  {
    id: "general-electrical",
    name: "General Electrical",
    parentId: undefined,
    children: [
      "socket-outlet",
      "lighting-circuit",
      "control-panel",
      "cable-tray",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "socket-outlet",
    name: "Socket / Outlet",
    parentId: "general-electrical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "lighting-circuit",
    name: "Lighting Circuit",
    parentId: "general-electrical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "control-panel",
    name: "Control Panel",
    parentId: "general-electrical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "cable-tray",
    name: "Cable Tray / Containment",
    parentId: "general-electrical",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // ==================== LIFE SAFETY ====================

  // Fire Alarm Systems
  {
    id: "fire-alarm-systems",
    name: "Fire Alarm Systems",
    parentId: undefined,
    children: [
      "fire-alarm-panel",
      "manual-call-point",
      "smoke-heat-detector",
      "sounder-beacon",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fire-alarm-panel",
    name: "Fire Alarm Control Panel",
    parentId: "fire-alarm-systems",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "manual-call-point",
    name: "Manual Call Point",
    parentId: "fire-alarm-systems",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "smoke-heat-detector",
    name: "Smoke / Heat Detector",
    parentId: "fire-alarm-systems",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "sounder-beacon",
    name: "Sounder / Beacon",
    parentId: "fire-alarm-systems",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Emergency Lighting
  {
    id: "emergency-lighting",
    name: "Emergency Lighting",
    parentId: undefined,
    children: ["emergency-light-fitting"],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "emergency-light-fitting",
    name: "Emergency Light Fitting",
    parentId: "emergency-lighting",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Fire Suppression
  {
    id: "fire-suppression",
    name: "Fire Suppression",
    parentId: undefined,
    children: [
      "sprinkler-pump",
      "sprinkler-head",
      "gas-suppression-cylinder",
      "fire-extinguisher",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "sprinkler-pump",
    name: "Sprinkler Pump",
    parentId: "fire-suppression",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "sprinkler-head",
    name: "Sprinkler Head",
    parentId: "fire-suppression",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "gas-suppression-cylinder",
    name: "Gas Suppression Cylinder",
    parentId: "fire-suppression",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fire-extinguisher",
    name: "Fire Extinguisher",
    parentId: "fire-suppression",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Fire Safety Infrastructure
  {
    id: "fire-safety-infrastructure",
    name: "Fire Safety Infrastructure",
    parentId: undefined,
    children: ["fire-door", "fire-curtain", "fire-damper"],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fire-door",
    name: "Fire Door",
    parentId: "fire-safety-infrastructure",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fire-curtain",
    name: "Fire Curtain",
    parentId: "fire-safety-infrastructure",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "fire-damper",
    name: "Fire Damper",
    parentId: "fire-safety-infrastructure",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // ==================== SECURITY ====================

  // CCTV
  {
    id: "cctv",
    name: "CCTV",
    parentId: undefined,
    children: ["cctv-camera", "nvr", "dvr", "cctv-power-supply"],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "cctv-camera",
    name: "CCTV Camera",
    parentId: "cctv",
    children: [],
    systemAttributes: [
      { attributeId: "resolution", isEnabled: true, order: 0 },
      { attributeId: "night-vision-range", isEnabled: true, order: 1 },
      { attributeId: "ptz-capability", isEnabled: true, order: 2 },
    ],
    customAttributes: [],
  },
  {
    id: "nvr",
    name: "Network Video Recorder (NVR)",
    parentId: "cctv",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "dvr",
    name: "DVR",
    parentId: "cctv",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "cctv-power-supply",
    name: "CCTV Power Supply",
    parentId: "cctv",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Intruder Alarm
  {
    id: "intruder-alarm",
    name: "Intruder Alarm",
    parentId: undefined,
    children: [
      "intruder-alarm-panel",
      "pir-sensor",
      "door-contact",
      "siren-bell",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "intruder-alarm-panel",
    name: "Intruder Alarm Panel",
    parentId: "intruder-alarm",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "pir-sensor",
    name: "PIR Sensor",
    parentId: "intruder-alarm",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "door-contact",
    name: "Door Contact",
    parentId: "intruder-alarm",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "siren-bell",
    name: "Siren / Bell Box",
    parentId: "intruder-alarm",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },

  // Access Control
  {
    id: "access-control",
    name: "Access Control",
    parentId: undefined,
    children: [
      "access-control-reader",
      "door-controller",
      "intercom",
      "electric-lock",
    ],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "access-control-reader",
    name: "Access Control Reader",
    parentId: "access-control",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "door-controller",
    name: "Door Controller",
    parentId: "access-control",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "intercom",
    name: "Intercom",
    parentId: "access-control",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
  {
    id: "electric-lock",
    name: "Electric Lock",
    parentId: "access-control",
    children: [],
    systemAttributes: [],
    customAttributes: [],
  },
];

// Core attributes that apply to all assets
export const coreAttributes: CoreAttribute[] = [
  // Asset Information
  {
    id: "core-asset-id",
    label: "Asset ID",
    type: "text",
    section: "asset-info",
    isEnabled: true,
    isRequired: true,
    description: "Internal asset ID for searching",
    detailedDescription: "This is an internal asset ID set by us. It allows you to search and find your asset easily.",
  },
  {
    id: "core-customer-reference",
    label: "Reference",
    type: "text",
    section: "asset-info",
    isEnabled: true,
    isRequired: false,
  },
  {
    id: "core-barcode",
    label: "Barcode",
    type: "text",
    section: "asset-info",
    isEnabled: true,
    isRequired: true,
    detailedDescription: "A unique identifier that can be scanned to quickly access asset information.",
  },
  {
    id: "core-category",
    label: "Category",
    type: "dropdown",
    section: "asset-info",
    isEnabled: true,
    isRequired: true,
    description: "Group assets by type using our category structure",
    detailedDescription: "We provide you with access to a robust category structure to help you get the most out of the system. Categories group assets by type, helping organize and filter your asset inventory. If you have any suggestions for improvements, please let us know.",
  },
  {
    id: "core-manufacturer",
    label: "Manufacturer",
    type: "dropdown",
    section: "asset-info",
    isEnabled: true,
    isRequired: true,
    detailedDescription: "This attribute displays manufacturers from your manufacturers list. Options are managed in the Manufacturers & Models section, not as predefined dropdown values.",
  },
  {
    id: "core-model",
    label: "Model",
    type: "dropdown",
    section: "asset-info",
    isEnabled: true,
    isRequired: true,
    detailedDescription: "This attribute displays models from your manufacturers list. Options are managed in the Manufacturers & Models section, not as predefined dropdown values.",
  },
  {
    id: "core-manufacturer-serial",
    label: "Manufacturer serial number",
    type: "text",
    section: "asset-info",
    isEnabled: true,
    isRequired: false,
  },
  {
    id: "core-date-manufacture",
    label: "Date of manufacture",
    type: "date",
    section: "asset-info",
    isEnabled: true,
    isRequired: false,
  },
  {
    id: "core-date-installation",
    label: "Date of installation",
    type: "date",
    section: "asset-info",
    isEnabled: true,
    isRequired: false,
  },
  {
    id: "core-date-last-service",
    label: "Date of last service",
    type: "date",
    section: "asset-info",
    isEnabled: true,
    isRequired: true,
    detailedDescription: "This is automatically updated by the system when service records are created. It helps track maintenance history and schedule future services.",
  },

  // End of Life
  {
    id: "core-end-of-life",
    label: "End of life date",
    type: "date",
    section: "dates",
    isEnabled: true,
    isRequired: false,
  },

  // Warranty
  {
    id: "core-warranty-expiry",
    label: "Warranty expiry date",
    type: "date",
    section: "warranty",
    isEnabled: true,
    isRequired: false,
  },

  // Status
  {
    id: "core-status",
    label: "Status",
    type: "dropdown",
    section: "status",
    isEnabled: true,
    isRequired: true,
    dropdownOptions: ["Active", "Inactive"],
  },

  // Contact & Location
  {
    id: "core-contact",
    label: "Site",
    type: "search",
    section: "contact",
    isEnabled: true,
    isRequired: true,
    description: "The site where this asset is located",
  },
  {
    id: "core-location",
    label: "Location",
    type: "text",
    section: "contact",
    isEnabled: true,
    isRequired: true,
    description: "Physical location of the asset",
    detailedDescription: "The physical location where the asset is installed or stored. This helps you organize and find assets by their location.",
  },

  // Condition
  {
    id: "core-condition",
    label: "Condition",
    type: "dropdown",
    section: "status",
    isEnabled: true,
    isRequired: true,
    dropdownOptions: ["Poor", "Fair", "Good", "Excellent", "Unknown"],
  },
];

// Manufacturers with models
export const manufacturers: Manufacturer[] = [
  {
    id: "vaillant",
    name: "Vaillant",
    models: [
      { id: "ecotec-pro", name: "ecoTEC Pro" },
      { id: "ecotec-plus", name: "ecoTEC Plus" },
    ],
    usedByCategories: ["boiler"],
  },
  {
    id: "worcester-bosch",
    name: "Worcester Bosch",
    models: [
      { id: "greenstar", name: "Greenstar" },
      { id: "cdi-compact", name: "CDI Compact" },
    ],
    usedByCategories: ["boiler"],
  },
  {
    id: "grundfos",
    name: "Grundfos",
    models: [
      { id: "ups-series", name: "UPS Series" },
      { id: "magna-series", name: "Magna Series" },
    ],
    usedByCategories: ["pump"],
  },
  {
    id: "hikvision",
    name: "Hikvision",
    models: [
      { id: "ds-series", name: "DS Series" },
      { id: "colorvu", name: "ColorVu" },
    ],
    usedByCategories: ["cctv-camera", "nvr"],
  },
  {
    id: "honeywell",
    name: "Honeywell",
    models: [
      { id: "galaxy", name: "Galaxy" },
      { id: "dimension", name: "Dimension" },
    ],
    usedByCategories: ["fire-alarm-panel", "intruder-alarm-panel"],
  },
];
