export interface Job {
  id: string;
  jobRef: string;
  site: string;
  parent: string;
  completed: string;
  status: "Scheduled" | "In progress" | "Invoiced" | "Complete";
  selling: number;
  leftToInvoice: number;
  progress: number; // 0-100
  jobType: "home_repair" | "stacks";
}

export const mockJobs: Job[] = [
  {
    id: "1",
    jobRef: "381910",
    site: "Next White Rose Leeds",
    parent: "Next Head Office",
    completed: "18 Mar 2024",
    status: "Scheduled",
    selling: 8393.0,
    leftToInvoice: 1000.0,
    progress: 85,
    jobType: "home_repair",
  },
  {
    id: "2",
    jobRef: "382011",
    site: "John Lewis Leeds",
    parent: "John Lewis Head Office",
    completed: "5 Mar – 25 Apr 2024",
    status: "In progress",
    selling: 7450.0,
    leftToInvoice: 500.0,
    progress: 95,
    jobType: "stacks",
  },
  {
    id: "3",
    jobRef: "382112",
    site: "John Lewis Liverpool",
    parent: "John Lewis Head Office",
    completed: "15 Jan – 30 Mar 2024",
    status: "In progress",
    selling: 9200.0,
    leftToInvoice: 1200.0,
    progress: 55,
    jobType: "stacks",
  },
  {
    id: "4",
    jobRef: "382112",
    site: "John Lewis Sheffield",
    parent: "John Lewis Head Office",
    completed: "15 Jan – 30 Mar 2024",
    status: "In progress",
    selling: 9200.0,
    leftToInvoice: 1200.0,
    progress: 55,
    jobType: "stacks",
  },
  {
    id: "5",
    jobRef: "382112",
    site: "John Lewis York",
    parent: "John Lewis Head Office",
    completed: "15 Jan – 30 Mar 2024",
    status: "In progress",
    selling: 9200.0,
    leftToInvoice: 1200.0,
    progress: 55,
    jobType: "stacks",
  },
  {
    id: "6",
    jobRef: "382213",
    site: "Next Yellow Daffodil Liverpool",
    parent: "Next Branch",
    completed: "20 Feb – 10 Apr 2024",
    status: "Invoiced",
    selling: 6850.0,
    leftToInvoice: 0.0,
    progress: 100,
    jobType: "stacks",
  },
  {
    id: "7",
    jobRef: "382314",
    site: "B&Q Manchester Central",
    parent: "B&Q Head Office",
    completed: "12 Apr 2024",
    status: "Scheduled",
    selling: 5200.0,
    leftToInvoice: 5200.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "8",
    jobRef: "382415",
    site: "IKEA Warrington",
    parent: "IKEA Head Office",
    completed: "1 Mar – 15 Apr 2024",
    status: "In progress",
    selling: 12500.0,
    leftToInvoice: 3500.0,
    progress: 72,
    jobType: "stacks",
  },
  {
    id: "9",
    jobRef: "382516",
    site: "Homebase Birmingham",
    parent: "Homebase UK",
    completed: "28 Feb 2024",
    status: "Complete",
    selling: 4300.0,
    leftToInvoice: 4300.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "10",
    jobRef: "382617",
    site: "Wickes Bradford",
    parent: "Wickes Group",
    completed: "10 Jan – 20 Mar 2024",
    status: "In progress",
    selling: 8750.0,
    leftToInvoice: 2100.0,
    progress: 76,
    jobType: "stacks",
  },
  {
    id: "11",
    jobRef: "382718",
    site: "Screwfix Newcastle",
    parent: "Screwfix Direct",
    completed: "5 Apr 2024",
    status: "Scheduled",
    selling: 3200.0,
    leftToInvoice: 3200.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "12",
    jobRef: "382819",
    site: "Toolstation Leeds",
    parent: "Toolstation Ltd",
    completed: "22 Feb – 8 Apr 2024",
    status: "In progress",
    selling: 6100.0,
    leftToInvoice: 1800.0,
    progress: 70,
    jobType: "stacks",
  },
  {
    id: "13",
    jobRef: "382920",
    site: "Travis Perkins Sheffield",
    parent: "Travis Perkins PLC",
    completed: "15 Mar 2024",
    status: "Complete",
    selling: 9500.0,
    leftToInvoice: 9500.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "14",
    jobRef: "383021",
    site: "Jewson Nottingham",
    parent: "Jewson Ltd",
    completed: "8 Feb – 30 Mar 2024",
    status: "In progress",
    selling: 7800.0,
    leftToInvoice: 2400.0,
    progress: 69,
    jobType: "stacks",
  },
  {
    id: "15",
    jobRef: "383122",
    site: "Selco Bristol",
    parent: "Selco Builders",
    completed: "20 Apr 2024",
    status: "Scheduled",
    selling: 4500.0,
    leftToInvoice: 4500.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "16",
    jobRef: "383223",
    site: "Howdens Southampton",
    parent: "Howdens Joinery",
    completed: "1 Feb – 25 Mar 2024",
    status: "Invoiced",
    selling: 11200.0,
    leftToInvoice: 0.0,
    progress: 100,
    jobType: "stacks",
  },
  {
    id: "17",
    jobRef: "383324",
    site: "MKM Building Supplies Derby",
    parent: "MKM Group",
    completed: "18 Mar 2024",
    status: "Complete",
    selling: 5600.0,
    leftToInvoice: 5600.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "18",
    jobRef: "383425",
    site: "Buildbase Leicester",
    parent: "Buildbase Ltd",
    completed: "12 Jan – 15 Apr 2024",
    status: "In progress",
    selling: 8900.0,
    leftToInvoice: 3200.0,
    progress: 64,
    jobType: "stacks",
  },
  {
    id: "19",
    jobRef: "383526",
    site: "Topps Tiles Coventry",
    parent: "Topps Tiles PLC",
    completed: "25 Apr 2024",
    status: "Scheduled",
    selling: 2800.0,
    leftToInvoice: 2800.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "20",
    jobRef: "383627",
    site: "Tile Giant Oxford",
    parent: "Tile Giant Ltd",
    completed: "5 Feb – 20 Mar 2024",
    status: "In progress",
    selling: 4100.0,
    leftToInvoice: 1200.0,
    progress: 71,
    jobType: "stacks",
  },
  {
    id: "21",
    jobRef: "383728",
    site: "CTD Tiles Cambridge",
    parent: "CTD Group",
    completed: "10 Mar 2024",
    status: "Complete",
    selling: 3500.0,
    leftToInvoice: 3500.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "22",
    jobRef: "383829",
    site: "Porcelanosa London",
    parent: "Porcelanosa UK",
    completed: "1 Jan – 28 Feb 2024",
    status: "Invoiced",
    selling: 15800.0,
    leftToInvoice: 0.0,
    progress: 100,
    jobType: "stacks",
  },
  {
    id: "23",
    jobRef: "383930",
    site: "Magnet Kitchens Glasgow",
    parent: "Magnet Ltd",
    completed: "22 Apr 2024",
    status: "Scheduled",
    selling: 7200.0,
    leftToInvoice: 7200.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "24",
    jobRef: "384031",
    site: "Wren Kitchens Edinburgh",
    parent: "Wren Kitchens Ltd",
    completed: "15 Feb – 10 Apr 2024",
    status: "In progress",
    selling: 18500.0,
    leftToInvoice: 6800.0,
    progress: 63,
    jobType: "stacks",
  },
  {
    id: "25",
    jobRef: "384132",
    site: "Symphony Kitchens Cardiff",
    parent: "Symphony Group",
    completed: "8 Mar 2024",
    status: "Complete",
    selling: 9800.0,
    leftToInvoice: 9800.0,
    progress: 100,
    jobType: "home_repair",
  },
  // Additional jobs for pagination testing
  {
    id: "26",
    jobRef: "384233",
    site: "Currys PC World Milton Keynes",
    parent: "Currys Group",
    completed: "5 May 2024",
    status: "Scheduled",
    selling: 4200.0,
    leftToInvoice: 4200.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "27",
    jobRef: "384334",
    site: "Argos Reading",
    parent: "Sainsbury's Argos",
    completed: "10 Mar – 20 Apr 2024",
    status: "In progress",
    selling: 6700.0,
    leftToInvoice: 2300.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "28",
    jobRef: "384435",
    site: "Halfords Bristol",
    parent: "Halfords Group",
    completed: "15 Apr 2024",
    status: "Complete",
    selling: 3100.0,
    leftToInvoice: 3100.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "29",
    jobRef: "384536",
    site: "Pets at Home Chester",
    parent: "Pets at Home Group",
    completed: "1 Feb – 28 Mar 2024",
    status: "In progress",
    selling: 5400.0,
    leftToInvoice: 1800.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "30",
    jobRef: "384637",
    site: "Sports Direct Newcastle",
    parent: "Frasers Group",
    completed: "25 Apr 2024",
    status: "Scheduled",
    selling: 8900.0,
    leftToInvoice: 8900.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "31",
    jobRef: "384738",
    site: "House of Fraser Birmingham",
    parent: "Frasers Group",
    completed: "20 Feb – 15 Apr 2024",
    status: "In progress",
    selling: 12300.0,
    leftToInvoice: 4100.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "32",
    jobRef: "384839",
    site: "Debenhams Manchester",
    parent: "Boohoo Group",
    completed: "10 Mar 2024",
    status: "Complete",
    selling: 7600.0,
    leftToInvoice: 7600.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "33",
    jobRef: "384940",
    site: "TK Maxx Liverpool",
    parent: "TJX Companies",
    completed: "5 Jan – 20 Mar 2024",
    status: "In progress",
    selling: 9200.0,
    leftToInvoice: 3100.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "34",
    jobRef: "385041",
    site: "Matalan Leeds",
    parent: "Matalan Retail",
    completed: "30 Apr 2024",
    status: "Scheduled",
    selling: 4800.0,
    leftToInvoice: 4800.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "35",
    jobRef: "385142",
    site: "Primark Sheffield",
    parent: "Associated British Foods",
    completed: "15 Feb – 10 Apr 2024",
    status: "In progress",
    selling: 15600.0,
    leftToInvoice: 5200.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "36",
    jobRef: "385243",
    site: "River Island Glasgow",
    parent: "River Island Fashion",
    completed: "20 Mar 2024",
    status: "Complete",
    selling: 6300.0,
    leftToInvoice: 6300.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "37",
    jobRef: "385344",
    site: "New Look Edinburgh",
    parent: "New Look Retail",
    completed: "1 Mar – 25 Apr 2024",
    status: "In progress",
    selling: 7100.0,
    leftToInvoice: 2400.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "38",
    jobRef: "385445",
    site: "H&M Cardiff",
    parent: "H&M Group",
    completed: "5 May 2024",
    status: "Scheduled",
    selling: 11200.0,
    leftToInvoice: 11200.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "39",
    jobRef: "385546",
    site: "Zara Bristol",
    parent: "Inditex Group",
    completed: "10 Feb – 5 Apr 2024",
    status: "In progress",
    selling: 13800.0,
    leftToInvoice: 4600.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "40",
    jobRef: "385647",
    site: "Uniqlo London",
    parent: "Fast Retailing",
    completed: "25 Mar 2024",
    status: "Complete",
    selling: 8400.0,
    leftToInvoice: 8400.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "41",
    jobRef: "385748",
    site: "Gap Oxford Street",
    parent: "Gap Inc",
    completed: "15 Jan – 30 Mar 2024",
    status: "In progress",
    selling: 9900.0,
    leftToInvoice: 3300.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "42",
    jobRef: "385849",
    site: "Superdry Brighton",
    parent: "Superdry PLC",
    completed: "10 May 2024",
    status: "Scheduled",
    selling: 5700.0,
    leftToInvoice: 5700.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "43",
    jobRef: "385950",
    site: "Ted Baker Nottingham",
    parent: "Authentic Brands",
    completed: "20 Feb – 15 Apr 2024",
    status: "In progress",
    selling: 7800.0,
    leftToInvoice: 2600.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "44",
    jobRef: "386051",
    site: "Moss Bros Leicester",
    parent: "Moss Bros Group",
    completed: "5 Apr 2024",
    status: "Complete",
    selling: 4100.0,
    leftToInvoice: 4100.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "45",
    jobRef: "386152",
    site: "Clarks Southampton",
    parent: "Clarks Shoes",
    completed: "1 Mar – 20 Apr 2024",
    status: "In progress",
    selling: 6200.0,
    leftToInvoice: 2100.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "46",
    jobRef: "386253",
    site: "Schuh Coventry",
    parent: "Genesco Inc",
    completed: "15 May 2024",
    status: "Scheduled",
    selling: 3800.0,
    leftToInvoice: 3800.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "47",
    jobRef: "386354",
    site: "JD Sports Wolverhampton",
    parent: "JD Sports Fashion",
    completed: "10 Feb – 5 Apr 2024",
    status: "In progress",
    selling: 8600.0,
    leftToInvoice: 2900.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "48",
    jobRef: "386455",
    site: "Footlocker Sunderland",
    parent: "Foot Locker Inc",
    completed: "30 Mar 2024",
    status: "Complete",
    selling: 5900.0,
    leftToInvoice: 5900.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "49",
    jobRef: "386556",
    site: "Size? Middlesbrough",
    parent: "JD Sports Fashion",
    completed: "25 Jan – 15 Apr 2024",
    status: "In progress",
    selling: 4300.0,
    leftToInvoice: 1400.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "50",
    jobRef: "386657",
    site: "Office Shoes York",
    parent: "Office Holdings",
    completed: "20 May 2024",
    status: "Scheduled",
    selling: 2900.0,
    leftToInvoice: 2900.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "51",
    jobRef: "386758",
    site: "Kurt Geiger Harrogate",
    parent: "Kurt Geiger Ltd",
    completed: "5 Mar – 25 Apr 2024",
    status: "In progress",
    selling: 7400.0,
    leftToInvoice: 2500.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "52",
    jobRef: "386859",
    site: "Boots Pharmacy Hull",
    parent: "Walgreens Boots Alliance",
    completed: "10 Apr 2024",
    status: "Complete",
    selling: 6100.0,
    leftToInvoice: 6100.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "53",
    jobRef: "386960",
    site: "Superdrug Grimsby",
    parent: "A.S. Watson Group",
    completed: "15 Feb – 10 Apr 2024",
    status: "In progress",
    selling: 3600.0,
    leftToInvoice: 1200.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "54",
    jobRef: "387061",
    site: "Savers Scunthorpe",
    parent: "A.S. Watson Group",
    completed: "25 May 2024",
    status: "Scheduled",
    selling: 2100.0,
    leftToInvoice: 2100.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "55",
    jobRef: "387162",
    site: "Lloyds Pharmacy Doncaster",
    parent: "Aurelius Equity",
    completed: "20 Jan – 15 Mar 2024",
    status: "In progress",
    selling: 4800.0,
    leftToInvoice: 1600.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "56",
    jobRef: "387263",
    site: "Holland & Barrett Rotherham",
    parent: "The Nature's Bounty Co",
    completed: "5 Apr 2024",
    status: "Complete",
    selling: 3200.0,
    leftToInvoice: 3200.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "57",
    jobRef: "387364",
    site: "The Body Shop Barnsley",
    parent: "Natura & Co",
    completed: "10 Mar – 30 Apr 2024",
    status: "In progress",
    selling: 5100.0,
    leftToInvoice: 1700.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "58",
    jobRef: "387465",
    site: "Lush Wakefield",
    parent: "Lush Ltd",
    completed: "30 May 2024",
    status: "Scheduled",
    selling: 4400.0,
    leftToInvoice: 4400.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "59",
    jobRef: "387566",
    site: "Space NK Huddersfield",
    parent: "Manzanita Capital",
    completed: "25 Feb – 20 Apr 2024",
    status: "In progress",
    selling: 6800.0,
    leftToInvoice: 2300.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "60",
    jobRef: "387667",
    site: "Sephora Bradford",
    parent: "LVMH",
    completed: "15 Apr 2024",
    status: "Complete",
    selling: 9300.0,
    leftToInvoice: 9300.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "61",
    jobRef: "387768",
    site: "Waterstones Halifax",
    parent: "Elliott Advisors",
    completed: "5 Feb – 25 Mar 2024",
    status: "In progress",
    selling: 4600.0,
    leftToInvoice: 1500.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "62",
    jobRef: "387869",
    site: "WHSmith Preston",
    parent: "WHSmith PLC",
    completed: "5 Jun 2024",
    status: "Scheduled",
    selling: 3700.0,
    leftToInvoice: 3700.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "63",
    jobRef: "387970",
    site: "Ryman Blackburn",
    parent: "Ryman Group",
    completed: "20 Mar – 15 May 2024",
    status: "In progress",
    selling: 2800.0,
    leftToInvoice: 900.0,
    progress: 68,
    jobType: "stacks",
  },
  {
    id: "64",
    jobRef: "388071",
    site: "Staples Bolton",
    parent: "Staples Inc",
    completed: "25 Apr 2024",
    status: "Complete",
    selling: 5400.0,
    leftToInvoice: 5400.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "65",
    jobRef: "388172",
    site: "Smyths Toys Bury",
    parent: "Smyths Toys Group",
    completed: "10 Jan – 5 Apr 2024",
    status: "In progress",
    selling: 8100.0,
    leftToInvoice: 2700.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "66",
    jobRef: "388273",
    site: "The Entertainer Oldham",
    parent: "The Entertainer Group",
    completed: "10 Jun 2024",
    status: "Scheduled",
    selling: 4900.0,
    leftToInvoice: 4900.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "67",
    jobRef: "388374",
    site: "Build-A-Bear Stockport",
    parent: "Build-A-Bear Workshop",
    completed: "15 Feb – 10 Apr 2024",
    status: "In progress",
    selling: 3400.0,
    leftToInvoice: 1100.0,
    progress: 68,
    jobType: "stacks",
  },
  {
    id: "68",
    jobRef: "388475",
    site: "Game Ashton",
    parent: "Frasers Group",
    completed: "5 May 2024",
    status: "Complete",
    selling: 6200.0,
    leftToInvoice: 6200.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "69",
    jobRef: "388576",
    site: "CeX Rochdale",
    parent: "CeX Ltd",
    completed: "25 Mar – 20 May 2024",
    status: "In progress",
    selling: 2600.0,
    leftToInvoice: 900.0,
    progress: 65,
    jobType: "stacks",
  },
  {
    id: "70",
    jobRef: "388677",
    site: "Music Magpie Wigan",
    parent: "musicMagpie PLC",
    completed: "15 Jun 2024",
    status: "Scheduled",
    selling: 1800.0,
    leftToInvoice: 1800.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "71",
    jobRef: "388778",
    site: "Currys Warrington",
    parent: "Currys Group",
    completed: "1 Mar – 25 Apr 2024",
    status: "In progress",
    selling: 7300.0,
    leftToInvoice: 2400.0,
    progress: 67,
    jobType: "stacks",
  },
  {
    id: "72",
    jobRef: "388879",
    site: "AO.com Crewe",
    parent: "AO World PLC",
    completed: "10 May 2024",
    status: "Complete",
    selling: 8700.0,
    leftToInvoice: 8700.0,
    progress: 100,
    jobType: "home_repair",
  },
  {
    id: "73",
    jobRef: "388980",
    site: "Euronics Stoke",
    parent: "Euronics International",
    completed: "20 Feb – 15 Apr 2024",
    status: "In progress",
    selling: 4100.0,
    leftToInvoice: 1400.0,
    progress: 66,
    jobType: "stacks",
  },
  {
    id: "74",
    jobRef: "389081",
    site: "Hughes Electrical Derby",
    parent: "Hughes Electrical",
    completed: "20 Jun 2024",
    status: "Scheduled",
    selling: 5600.0,
    leftToInvoice: 5600.0,
    progress: 0,
    jobType: "home_repair",
  },
  {
    id: "75",
    jobRef: "389182",
    site: "Robert Dyas Northampton",
    parent: "Robert Dyas Holdings",
    completed: "5 Mar – 30 Apr 2024",
    status: "In progress",
    selling: 3900.0,
    leftToInvoice: 1300.0,
    progress: 67,
    jobType: "stacks",
  },
];

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    minimumFractionDigits: 2,
  }).format(amount);
}
